### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by rupeshkumar22** [tyron12233/ApkBuilder#5]
Hi,

The project is interesting. I need some more information about the native shared libraries (libaapt2.so) present in jni folder. How did you create these libraries? Did you use NDK/Cmake to create these libraries?

Thanks

**Comment by rupeshkumar22** [comment]
I have checked that `armeabi/libaapt2.so` is of armv7a type architecture. I haven't checked it running on various devices. Would it be compatible with armv8a and other architectures?

**Comment by tyron12233** [comment]
The native libraries were taken from OpenBlocks (https://github.com/OpenBlocksTeam/android-build-tools) as far as I know, armv8a can run legacy codes which in theory, should work.

**Comment by rupeshkumar22** [comment]
@tyron12233 thanks for informing!
